usb suspend tool

diff --git a/sususb b/sususb
--- a/sususb
+++ b/sususb
@@ -1,32 +1,4 @@
 #!/bin/bash
-#
-#  suspend-usb-device: an easy-to-use script to properly put an USB
-#  device into suspend mode that can then be unplugged safely
-#
-#  Copyright (C) 2009, Yan Li <elliot.li.tech@gmail.com>
-#
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, either version 3 of the License, or
-#  (at your option) any later version.
-#
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-#  To reach the auther, please write an email to the address as stated
-#  above.
-
-#  ACKNOWLEDGEMENTS:
-#      Christian Schmitt <chris@ilovelinux.de> for firewire supporting
-#      David <d.tonhofer@m-plify.com> for improving parent device
-#      search and verbose output message
-
-
 usage()
 {
     cat<<EOF
@@ -59,7 +31,8 @@ EOF
 set -e -u
 
 SHOW_DEVICE_ONLY=0
-VERBOSE=0
+VERBOSE=1
+REMOVE=0
 while getopts "vlh" opt; do
     case "$opt" in
         h)
@@ -72,6 +45,9 @@ while getopts "vlh" opt; do
         v)
             VERBOSE=1
             ;;
+	r)
+	    REMOVE=1
+	    ;;
         ?)
             echo
             usage
@@ -88,25 +64,16 @@ fi
 
 # mount checking
 if mount | grep "^${DEV_NAME}[[:digit:]]* "; then
-    1>&2 echo
     1>&2 echo "the above disk or partition is still mounted, can't suspend device"
-    1>&2 echo "unmount it first using umount"
+    1>&2 echo "umounting ${DEV_NAME}"
+    umount ${DEV_NAME} 
+fi
+# mount double-checking
+if mount | grep "^${DEV_NAME}[[:digit:]]* "; then
+    1>&2 echo "the above disk or partition is still mounted, can't suspend device"
+    1>&2 echo "umounting ${DEV_NAME}"
     exit 1
 fi
-
-# looking for the parent of the device with type "usb-storage:usb", it
-# is the grand-parent device of the SCSI host, and it's devpath is
-# like
-# /devices/pci0000:00/0000:00:1d.7/usb5/5-8 (or /fw5/fw5-8 for firewire devices)
-
-# without an USB hub, the device path looks like:
-# /devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host5/target5:0:0/5:0:0:0
-# here the grand-parent of host5 is 2-1
-
-# when there's a USB HUB, the device path is like:
-# /devices/pci0000:00/0000:00:1d.0/usb5/5-2/5-2.2/5-2.2:1.0/host4/target4:0:0/4:0:0:0
-# and the grand-parent of host4 is 5-2.2
-
 DEVICE=$(udevadm info --query=path --name=${DEV_NAME} --attribute-walk | \
     egrep "looking at parent device" | head -1 | \
     sed -e "s/.*looking at parent device '\(\/devices\/.*\)\/.*\/host.*/\1/g")
@@ -143,6 +110,7 @@ fi
 # ignore errors with "|| true"
 [[ $VERBOSE == 1 ]] && echo "Syncing device $DEV_NAME"
 sdparm --command=sync "$DEV_NAME" >/dev/null || true
+sleep 5
 # send SCSI stop command
 [[ $VERBOSE == 1 ]] && echo "Stopping device $DEV_NAME"
 sdparm --command=stop "$DEV_NAME" >/dev/null
@@ -153,7 +121,6 @@ if [[ "${DEV_BUS_ID}" == fw* ]]
 then
     echo -n "${DEV_BUS_ID}" > /sys/bus/firewire/drivers/sbp2/unbind
 else
-    echo -n "${DEV_BUS_ID}" > /sys/bus/usb/drivers/usb/unbind
 
     # suspend it if it's an USB device (we have no way to suspend a
     # firewire device yet)
@@ -162,23 +129,11 @@ else
     [[ $VERBOSE == 1 ]] && echo "Checking whether $DEVICE can be suspended"
     POWER_LEVEL_FILE=/sys${DEVICE}/power/control
     POWER_SUSPEND_FILE=/sys${DEVICE}/power/autosuspend
-    if [ ! -f "$POWER_LEVEL_FILE" ]; then
-        1>&2 cat<<EOF
-It's safe to remove the USB device now but better can be done. The
-power level control file $POWER_LEVEL_FILE
-doesn't exist on the system so I have no way to put the USB device
-into suspend mode, perhaps you don't have CONFIG_USB_SUSPEND enabled
-in your running kernel.
-
-Read
-http://elliotli.blogspot.com/2009/01/safely-remove-usb-hard-drive-in-linux.html
-for an detailed explanation.
-EOF
-        exit 3
-    fi
-
     [[ $VERBOSE == 1 ]] && echo "Suspending $DEVICE by writing to $POWER_LEVEL_FILE"
-    echo '0' > "$POWER_SUSPEND_FILE"
     echo 'auto' > "$POWER_LEVEL_FILE"
-    sleep 2
+    echo '0' > "$POWER_SUSPEND_FILE"
+    echo -n "${DEV_BUS_ID}" > /sys/bus/usb/drivers/usb/unbind
+    sleep 1
+    [[ $REMOVE == 1 ]] && echo "Remove device"
+    [[ $REMOVE == 1 ]] && echo "1" > /sys${DEVICE}/remove
 fi
